-- ============================================================
-- 06_magnitude_analysis.sql
-- ============================================================
--
-- PURPOSE:
--   Compare revenue and volume across different dimensions to find where the business is concentrated. 
--   Covers country, product category, subcategory, and average price per unit.
--   This is where you start answering the
--   question: "where is the money actually coming from?"
--
-- WARNING:
--   All queries here use INNER JOIN, which means any sales records with no matching customer or product will besilently excluded.
--   If the data quality checks from script 02 flagged NULLs on customer_key or product_key,those rows will drop out of these results without warning.
--   Also, the avg_price_per_unit calculation uses NULLIF on quantity — if a category has only zero-quantity rows;', it will return NULL here.
-- ============================================================


-- ── Revenue by Country ───────────────────────────────────────

-- See which markets drive the most revenue and orders
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue,
    COUNT(DISTINCT f.order_number) AS total_orders,
    COUNT(DISTINCT f.customer_key) AS unique_customers
FROM gold.fact_sales f
JOIN gold.dim_customers c 
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;


-- ── Revenue by Product Category ──────────────────────────────

-- Which categories actually move the needle?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.quantity) AS total_units,
    COUNT(f.order_number) AS total_orders
FROM gold.fact_sales f
JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- ── Revenue by Subcategory ───────────────────────────────────

-- One level deeper than category — some subcategories hide inside a strong category
SELECT
    p.category,
    p.subcategory,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.quantity) AS total_units
FROM gold.fact_sales f
JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY p.category, p.subcategory
ORDER BY total_revenue DESC;


-- ── Average Revenue Per Unit by Category ─────────────────────

-- Total revenue can be misleading — this shows whether a category is premium or volume-driven
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.quantity) AS total_units,
    ROUND(SUM(f.sales_amount) * 1.0/ NULLIF(SUM(f.quantity), 0), 2) AS avg_price_per_unit
FROM gold.fact_sales f
JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY avg_price_per_unit DESC;

-- What is the total revenue generated by each customer.
SELECT
  c.customer_key,
  c.first_name,
  c.last_name,
  sum(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
  c.customer_key,
  c.first_name,
  c.last_name
ORDER BY total_revenue DESC
